micronaut:
  application:
    name: micronaut-benchmark
  server:
    port: 8080
    server-header: Micronaut
    date-header: false
  netty:
    event-loops:
      default:
        num-threads: ${processors:48}

netty:
  resource-leak-detector-level: DISABLED

datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    dialect: POSTGRES
    maximum-pool-size: ${processorsx2:48}
    transaction-per-operation: false
    allow-connection-per-operation: true

r2dbc:
  datasources:
    default:
      db-type: postgresql
      dialect: POSTGRES
      options:
        protocol: postgres
        initialSize: 0
        maxSize: ${processorsx2:48}

mongodb:
  package-names:
    benchmark
  uuid-representation: STANDARD
