micronaut:
  application:
    name: micronaut-benchmark
  server:
    port: 8080
    server-header: Micronaut
    date-header: false
    idle-timeout: -1
#  netty:
#    event-loops:
#      default:
#        num-threads: ${processors:48}

netty:
  resource-leak-detector-level: DISABLED

datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    dialect: POSTGRES
    maximum-pool-size: 1024
    minimum-idle: 512
    transaction-per-operation: false
    allow-connection-per-operation: true

r2dbc:
  datasources:
    default:
      db-type: postgresql
      dialect: POSTGRES
      options:
        protocol: postgres
        initialSize: 128
        maxSize: 1024

mongodb:
  package-names:
    benchmark
  uuid-representation: STANDARD
