micronaut:
  application:
    name: micronaut-benchmark
  server:
    port: 8080
    server-header: Micronaut
    date-header: false
    idle-timeout: -1s # Remove the idle check from the Netty pipeline

netty:
  resource-leak-detector-level: DISABLED
  default:
    allocator:
      max-order: 3

datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    dialect: POSTGRES
    maximum-pool-size: 512
    transaction-per-operation: false
    allow-connection-per-operation: true

r2dbc:
  datasources:
    default:
      db-type: postgresql
      dialect: POSTGRES
      options:
        protocol: postgres
        initialSize: 128
        maxSize: 512

mongodb:
  connection-pool:
    max-size: 1024
    min-size: 512
    max-connecting: 100
  package-names:
    benchmark
  uuid-representation: STANDARD
